#!/bin/bash
# Script de démarrage rapide pour Esther House

echo "🎭 Bienvenue dans Esther House!"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           ESTHER HOUSE - SETUP INITIAL COMPLÉTÉ ✅             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 Dépendances installées: ✅"
echo "⚙️  Configuration créée: ✅"
echo "📁 Structure de dossiers: ✅"
echo "📄 Documentation: ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 PROCHAINES ÉTAPES:"
echo ""
echo "1️⃣  CONFIGUREZ VOS VARIABLES D'ENVIRONNEMENT"
echo "   Éditez le fichier .env.local et ajoutez:"
echo "   - NEXT_PUBLIC_SUPABASE_URL"
echo "   - NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "   - STRIPE_SECRET_KEY"
echo ""
echo "2️⃣  DÉMARREZ LE SERVEUR DE DÉVELOPPEMENT"
echo "   npm run dev"
echo "   Visitez: http://localhost:3000"
echo ""
echo "3️⃣  CONFIGUREZ SUPABASE"
echo "   - Créez un compte: https://supabase.com"
echo "   - Suivez DATABASE_SETUP.md pour les migrations SQL"
echo ""
echo "4️⃣  CONFIGUREZ STRIPE"
echo "   - Créez un compte: https://stripe.com"
echo "   - Copier les clés d'API"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTATION:"
echo "   • README.md - Vue d'ensemble du projet"
echo "   • NEXT_STEPS.md - Checklist complète des tâches"
echo "   • DATABASE_SETUP.md - Configuration de la base de données"
echo ""
echo "🔗 RESSOURCES UTILES:"
echo "   • Next.js: https://nextjs.org"
echo "   • Supabase: https://supabase.com"
echo "   • Stripe: https://stripe.com"
echo "   • Tailwind: https://tailwindcss.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Bon développement! N'hésitez pas à consulter la documentation"
echo ""
